name = "PowerEdu"
uuid = "c724488d-05f0-4cbe-a654-015ca373493b"
authors = ["Ninad Kiran Gaikwad"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
